import Head from 'next/head'
import { Fragment } from 'react'
import { Layout } from '../components/Layout'
import { Top } from "../components/Top";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <Top />

        This is home page
      </Layout>
    </Fragment>
  )
}
